# Numpy

Материалы:
* Макрушин С.В. "Лекция 1: Библиотека Numpy"
* https://numpy.org/doc/stable/user/index.html
* https://numpy.org/doc/stable/reference/index.html

## Задачи для совместного разбора

1. Сгенерировать двухмерный массив `arr` размерности (4, 7), состоящий из случайных действительных чисел, равномерно распределенных в диапазоне от 0 до 20. Нормализовать значения массива с помощью преобразования вида  $𝑎𝑥+𝑏$  так, что после нормализации максимальный элемент масcива будет равен 1.0, минимальный 0.0

2. Создать матрицу 8 на 10 из случайных целых (используя модуль `numpy.random`) чисел из диапозона от 0 до 10 и найти в ней строку (ее индекс и вывести саму строку), в которой сумма значений минимальна.

3. Найти евклидово расстояние между двумя одномерными векторами одинаковой размерности.

4. Решить матричное уравнение `A*X*B=-C` - найти матрицу `X`. Где `A = [[-1, 2, 4], [-3, 1, 2], [-3, 0, 1]]`, `B=[[3, -1], [2, 1]]`, `C=[[7, 21], [11, 8], [8, 4]]`.

## Лабораторная работа №1

Замечание: при решении данных задач не подразумевается использования циклов или генераторов Python, если в задании не сказано обратного. Решение должно опираться на использования функционала библиотеки `numpy`.

In [1]:
import numpy as np


1. Файл `minutes_n_ingredients.csv` содержит информацию об идентификаторе рецепта, времени его выполнения в минутах и количестве необходимых ингредиентов. Считайте данные из этого файла в виде массива `numpy` типа `int32`, используя `np.loadtxt`. Выведите на экран первые 5 строк массива.

2. Вычислите среднее значение, минимум, максимум и медиану по каждому из столбцов, кроме первого.

In [2]:
a = np.loadtxt("minutes_n_ingredients.csv", dtype='int32', delimiter=",", skiprows=1)
print(a[0:5])
print()
print(np.max(a[:,1:], axis = 0))
print(np.min(a[:,1:], axis = 0))
print(np.mean(a[:,1:], axis = 0))
print(np.median(a[:,1:], axis = 0))
print()
print()
print()

[[127244     60     16]
 [ 23891     25      7]
 [ 94746     10      6]
 [ 67660      5      6]
 [157911     60     14]]

[2147483647         39]
[0 1]
[2.16010017e+04 9.05528000e+00]
[40.  9.]





3. Ограничьте сверху значения продолжительности выполнения рецепта значением квантиля $q_{0.75}$. 

In [4]:
q = np.quantile(a[:, 1], q=0.75)
a[:, 1] = a[:, 1].clip(max=q)
q

65.0

4. Посчитайте, для скольких рецептов указана продолжительность, равная нулю. Замените для таких строк значение в данном столбце на 1.

In [3]:
a = np.loadtxt("minutes_n_ingredients.csv", dtype='int32', delimiter=",", skiprows=1)
print(np.sum(a[:,1]==0))
a[a[:,1]==0, 1]=1
print(a)

479
[[127244     60     16]
 [ 23891     25      7]
 [ 94746     10      6]
 ...
 [498432     65     15]
 [370915      5      4]
 [ 81993    140     14]]


5. Посчитайте, сколько уникальных рецептов находится в датасете.

In [5]:
print(len(np.unique(a)))

100058


6. Сколько и каких различных значений кол-ва ингредиентов присутвует в рецептах из датасета?

In [6]:
print(len(np.unique(a[:,2])))

37


7. Создайте версию массива, содержащую информацию только о рецептах, состоящих не более чем из 5 ингредиентов.

In [7]:
меньше_5 = a[a[:,2]<=5].copy()
меньше_5

array([[446597,     15,      5],
       [204134,      5,      3],
       [ 25623,      6,      4],
       ...,
       [ 52088,     60,      5],
       [128811,     15,      4],
       [370915,      5,      4]], dtype=int32)

8. Для каждого рецепта посчитайте, сколько в среднем ингредиентов приходится на одну минуту рецепта. Найдите максимальное значение этой величины для всего датасета

In [ ]:
среднее_значение = a[:,2]/a[:,1]
среднее_значение.max()

(24.0, 0.381174261705681)

9. Вычислите среднее количество ингредиентов для топ-100 рецептов с наибольшей продолжительностью

In [ ]:
a[a[:, 1].argsort()][-100:][:, 2].mean()

6.61

10. Выберите случайным образом и выведите информацию о 10 различных рецептах

In [ ]:
a[np.random.randint(0, 100000, size=10)]

array([[  7788,     75,     12],
       [426089,     40,      7],
       [ 72082,     10,      8],
       [217910,    320,      8],
       [422979,     30,     12],
       [246658,    105,      9],
       [ 80908,    135,      8],
       [207223,     70,     11],
       [ 99077,    515,     10],
       [239392,     15,      6]], dtype=int32)

11. Выведите процент рецептов, кол-во ингредиентов в которых меньше среднего.

In [ ]:
ing = a[:, 2].mean()
len(a[a[:, 2] < ing]) / len(a) * 100

58.802

12. Назовем "простым" такой рецепт, длительность выполнения которого не больше 20 минут и кол-во ингредиентов в котором не больше 5. Создайте версию датасета с дополнительным столбцом, значениями которого являются 1, если рецепт простой, и 0 в противном случае.

In [ ]:
prostota = (a[:, 1] <= 20) & (a[:, 2] <= 5)
print(prostota)
prostota = prostota.astype(np.int32)

prostota = prostota[:, np.newaxis]
print(prostota)

data_prostota = np.hstack((a, prostota))
data_prostota

[False False False ... False  True False]
[[0]
 [0]
 [0]
 ...
 [0]
 [1]
 [0]]


array([[127244,     60,     16,      0],
       [ 23891,     25,      7,      0],
       [ 94746,     10,      6,      0],
       ...,
       [498432,     65,     15,      0],
       [370915,      5,      4,      1],
       [ 81993,    140,     14,      0]], dtype=int32)

13. Выведите процент "простых" рецептов в датасете

In [ ]:
len(data_prostota[data_prostota[:, 3] == 1]) / len(data_prostota) * 100

14. Разделим рецепты на группы по следующему правилу. Назовем рецепты короткими, если их продолжительность составляет менее 10 минут; стандартными, если их продолжительность составляет более 10, но менее 20 минут; и длинными, если их продолжительность составляет не менее 20 минут. Создайте трехмерный массив, где нулевая ось отвечает за номер группы (короткий, стандартный или длинный рецепт), первая ось - за сам рецепт и вторая ось - за характеристики рецепта. Выберите максимальное количество рецептов из каждой группы таким образом, чтобы было возможно сформировать трехмерный массив. Выведите форму полученного массива.

In [8]:
data = np.loadtxt("minutes_n_ingredients.csv", dtype='int32', delimiter=",", skiprows=1)
short = data[data[:, 1] < 10] 
standart = data[(data[:, 1] >= 10) & (data[:, 1] < 20)] 
long = data[data[:, 1] >= 20] 
stop = min([len(arr) for arr in [short, standart, long]]) 
np.array([short[:stop], standart[:stop], long[:stop]])

array([[[ 67660,      5,      6],
        [366174,      7,      9],
        [204134,      5,      3],
        ...,
        [420725,      5,      3],
        [  4747,      0,      9],
        [370915,      5,      4]],

       [[ 94746,     10,      6],
        [ 33941,     18,      9],
        [446597,     15,      5],
        ...,
        [  9831,     15,      7],
        [335859,     12,     14],
        [256812,     10,      3]],

       [[127244,     60,     16],
        [ 23891,     25,      7],
        [157911,     60,     14],
        ...,
        [168901,     25,      7],
        [392339,     35,     13],
        [206732,     45,     10]]], dtype=int32)